title: REBEKAH DUMAUP PHOTOGRAPHY
author: Rebekah Dumaup
email: rsdumaup@gmail.com
description: >-
    Hello, I'm Rebekah. I’m 29 years old and I am a potrait, family, wedding, and engagement photographer based in Salt Lake City, Utah.

    When I’m not shooting or editing, I love to go fishing, climbing, play videogames, cook new recipes, and take care of my dogs and chickens.

    Photography to me is a canvas for creativity and moments are the paint that give it life and color. I believe the most beautiful images are those that paint a genuine, authentic, honest, and precious moment in time. My goal is to capture these special moments in hopes that I can create something timeless for you to cherish.

    I would so love to meet you and capture your special moments, so please feel free to contact me.

social:
  facebook: Rebekah-Dumaup-Photography-256418628690429
  instagram: rebekah.dumaup
  github: rdumaup
  linkedin: rdumaup

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true

url: "https://rebekahdumaup.com"
